#!/bin/bash
theme="${FZF_THEME}"
if [[ -z "$theme" && -f "$HOME/.cache/theme" ]]; then
    read -r theme < "$HOME/.cache/theme"
fi
if [[ -z "$theme" ]]; then
    if defaults read -g AppleInterfaceStyle &>/dev/null; then
        theme="dark"
    else
        theme="light"
    fi
    mkdir -p "$HOME/.cache"
    echo "$theme" > "$HOME/.cache/theme"
fi

if [[ "$theme" == "light" ]]; then
    exec delta --features "catppuccin-latte" "$@"
else
    exec delta --features "catppuccin-macchiato" "$@"
fi
