#!/bin/bash
theme="${FZF_THEME}"
if [[ -z "$theme" && -f "$HOME/.cache/theme" ]]; then
    read -r theme < "$HOME/.cache/theme"
fi
if [[ -z "$theme" ]]; then
    theme="dark"
fi

if [[ "$theme" == "light" ]]; then
    exec delta --features "catppuccin-latte" "$@"
else
    exec delta --features "catppuccin-macchiato" "$@"
fi
