local application = require("hs.application")

Hyper:bind({}, "a", function() application.launchOrFocus("kitty") end)
Hyper:bind({}, "c", function() application.launchOrFocus("Calendar") end)
Hyper:bind({}, "d", function() application.launchOrFocus("Spotify") end)
Hyper:bind({}, "e", function() application.launchOrFocus("Mail") end)
Hyper:bind({}, "f", function() application.launchOrFocus("Finder") end)
Hyper:bind({}, "g", function() application.launchOrFocus("System Preferences") end)
Hyper:bind({}, "q", function() application.launchOrFocus("Signal") end)
Hyper:bind({}, "r", function() application.launchOrFocus("Notes") end)
Hyper:bind({}, "s", function() application.launchOrFocus("Safari") end)
Hyper:bind({}, "t", function() application.launchOrFocus("Calculator") end)
Hyper:bind({}, "v", function() application.launchOrFocus("Brave Browser") end)
Hyper:bind({}, "w", function() application.launchOrFocus("WhatsApp") end)
Hyper:bind({}, "x", function() application.launchOrFocus("Launchpad") end)
Hyper:bind({}, "z", function() application.launchOrFocus("Activity Monitor") end)

Hyper:bind({ "cmd" }, "g", function() application.launchOrFocus("App Store") end)
Hyper:bind({ "cmd" }, "r", function() application.launchOrFocus("Reminders") end)

Hyper:bind({ "cmd", "ctrl" }, "r", function() hs.reload() end)
Hyper:bind({ "cmd", "shift" }, "r", function() hs.reload() end)
