#!/usr/bin/env sh

yabai -m config                           \
  bottom_padding              10          \
  left_padding                10          \
  right_padding               10          \
  top_padding                 10          \
  window_gap                  10          \
  layout                      bsp         \
  split_ratio                 0.5         \
  split_type                  auto        \
  window_origin_display       focused     \
  window_zoom_persist         true        \
  insert_feedback_color       0xff9697d4

yabai -m rule --add app!="^(Brave Browser|Code|Firefox|IntelliJ IDEA|kitty|Safari)$" manage=off
yabai -m rule --add app="^Firefox$" title="^Library$" manage=off
yabai -m rule --add app="^IntelliJ IDEA$" title="(^IntelliJ IDEA CE and Plugin Updates|Evaluate|File Cache Conflict|Preferences|Project Structure|Plugins|Run/Debug Configurations|New Project|Select Modules|Settings|Welcome to IntelliJ IDEA)$" manage=off
yabai -m rule --add app="^Safari$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advanced)$" manage=off
