#!/usr/bin/env sh

yabai -m config bottom_padding               10
yabai -m config left_padding                 10
yabai -m config right_padding                10
yabai -m config top_padding                  10
yabai -m config window_gap                   10
yabai -m config layout                       bsp
yabai -m config split_ratio                  0.5
yabai -m config window_origin_display        focused
yabai -m config window_border                on
yabai -m config window_border_width          2
yabai -m config active_window_border_color   0xff888fce
yabai -m config normal_window_border_color   0x00cccccc
yabai -m config insert_feedback_color        0xff888fce

yabai -m rule --add app!="^(Brave Browser|Firefox|kitty|Safari)$" manage=off
