#!/usr/bin/env sh

yabai -m config bottom_padding               10
yabai -m config left_padding                 10
yabai -m config right_padding                10
yabai -m config top_padding                  10
yabai -m config window_gap                   10
yabai -m config split_ratio                  0.50
yabai -m config layout                       bsp
yabai -m config insert_feedback_color        0xff61afef

yabai -m rule --add app="^Activity Monitor$" manage=off grid=8:8:1:1:6:6
yabai -m rule --add app="^Alfred Preferences$" manage=off grid=8:8:1:1:6:6
yabai -m rule --add app="^App Store$" manage=off grid=8:8:1:1:6:6
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^Calendar$" manage=off grid=8:8:1:1:6:6
yabai -m rule --add app="^Discord$" manage=off grid=8:8:1:1:6:6
yabai -m rule --add app="^Disk Utility$" manage=off
yabai -m rule --add app="^Finder$" manage=off
yabai -m rule --add app="^Karabiner-Elements$" manage=off
yabai -m rule --add app="^Karabiner-EventViewer$" manage=off
yabai -m rule --add app="^Logi Options$" manage=off
yabai -m rule --add app="^Mail$" manage=off grid=8:8:1:1:6:6
yabai -m rule --add app="^Messages$" manage=off grid=8:8:1:1:6:6
yabai -m rule --add app="^Notes$" manage=off grid=8:8:1:1:6:6
yabai -m rule --add app="^Preview$" manage=off
yabai -m rule --add app="^Reminders$" manage=off
yabai -m rule --add app="^Signal$" manage=off grid=8:8:1:1:6:6
yabai -m rule --add app="^Skype$" manage=off grid=8:8:1:1:6:6
yabai -m rule --add app="^Spotify$" manage=off grid=8:8:1:1:6:6
yabai -m rule --add app="^System Information$" manage=off
yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="^VirtualBox$" manage=off grid=8:8:1:1:6:6
yabai -m rule --add app="^WhatsApp$" manage=off grid=8:8:1:1:6:6

#killall limelight &>/dev/null
#limelight &>/dev/null &
